// <auto-generated />
using System;
using AutoRepairService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoRepairService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918101927_AddCascadeDeleteToRelations")]
    partial class AddCascadeDeleteToRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Customer_Id");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Last4Digits")
                        .IsRequired()
                        .HasColumnType("char(4)");

                    b.Property<string>("ProcessorToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProcessorToken")
                        .IsUnique();

                    b.ToTable("Card_Table", null, t =>
                        {
                            t.HasCheckConstraint("CK_Card_Last4Digits", "[Last4Digits] LIKE '[0-9][0-9][0-9][0-9]'");
                        });
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DefaultAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Users_Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customer_Profile_Table", (string)null);
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.MechanicBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Bank_Name");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Holder_Name");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MechanicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Mechanic_Id");

                    b.HasKey("Id");

                    b.HasIndex("IBAN")
                        .IsUnique();

                    b.HasIndex("MechanicId");

                    b.ToTable("Mechanic_Bank_Accounts_Table", (string)null);
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.MechanicProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Bio")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CompletedJobsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("HourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Users_Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mechanic_Profile_Table", (string)null);
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Part_Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Parts_Table", null, t =>
                        {
                            t.HasCheckConstraint("CK_Parts_Quantity", "[Quantity] >= 0");
                        });
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.PayMent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CustomerCardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Customer_Card_Id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Customer_Id");

                    b.Property<Guid>("MechanicAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Mechanic_Account_Id");

                    b.Property<Guid>("MechanicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Mechanic_Id");

                    b.Property<DateTime>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Paid_At")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Service_Id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MechanicAccountId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("ServiceId");

                    b.ToTable("PayMents_Table", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Status", "LOWER([Status]) IN ('Pending', 'Done', 'Rejected', 'CoudlNotMake')");
                        });
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Users_Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profile_Table", (string)null);
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.ToTable("Roles_Table", (string)null);
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("AcceptedByMechanicAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Accepted_by_mechanic_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Customer_Id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Done_At");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("EstimatedHours");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MechanicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Mechanic_Id");

                    b.Property<decimal>("PartsPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Requested_At")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<decimal>("ServicePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Vehicle_Id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Service_Table", (string)null);
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.ServicePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Part_Id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Service_Id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("PartId", "ServiceId")
                        .IsUnique();

                    b.ToTable("Service_Parts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServiceParts_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("EmailVerificationToken");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("EmailVerificationTokenExpiresAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsEmailVerified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_table", (string)null);
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Role_Id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Users_Id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("Users_Roles_Table", (string)null);
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Users_Id");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Vehicle_Table", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehicle_Engine", "LOWER([Engine]) IN ('gasoline', 'diesel', 'hybrid', 'electric', 'plug-in hybrid')");

                            t.HasCheckConstraint("CK_Vehicle_PlateNumber", "[PlateNumber] LIKE '[A-Z][A-Z]-[0-9][0-9][0-9]-[A-Z][A-Z]' OR [PlateNumber] LIKE '[A-Z][A-Z][A-Z]-[0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_Vehicle_Transmission", "LOWER([Transmission]) IN ('automatic', 'manual', 'cvt', 'semi-automatic')");

                            t.HasCheckConstraint("CK_Vehicle_Year", "[Year] <= YEAR(GETDATE())");
                        });
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Card", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.CustomerProfile", "Customer")
                        .WithMany("Cards")
                        .HasForeignKey("CustomerId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.CustomerProfile", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.User", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("AutoRepairService.Domain.Entities.CustomerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.MechanicBankAccount", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.MechanicProfile", "MechanicProfile")
                        .WithMany("BankAccounts")
                        .HasForeignKey("MechanicId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MechanicProfile");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.MechanicProfile", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.User", "User")
                        .WithOne("MechanicProfile")
                        .HasForeignKey("AutoRepairService.Domain.Entities.MechanicProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.PayMent", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.Card", "CustomerCard")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRepairService.Domain.Entities.CustomerProfile", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRepairService.Domain.Entities.MechanicBankAccount", "MechanicAccount")
                        .WithMany("PayMents")
                        .HasForeignKey("MechanicAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRepairService.Domain.Entities.MechanicProfile", "Mechanic")
                        .WithMany("Payments")
                        .HasForeignKey("MechanicId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRepairService.Domain.Entities.Service", "Service")
                        .WithMany("Payments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerCard");

                    b.Navigation("Mechanic");

                    b.Navigation("MechanicAccount");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Profile", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("AutoRepairService.Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Service", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.CustomerProfile", "Customer")
                        .WithMany("Services")
                        .HasForeignKey("CustomerId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRepairService.Domain.Entities.MechanicProfile", "Mechanic")
                        .WithMany("Services")
                        .HasForeignKey("MechanicId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRepairService.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Services")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Mechanic");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.ServicePart", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.Part", "Part")
                        .WithMany("ServiceParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRepairService.Domain.Entities.Service", "Service")
                        .WithMany("ServiceParts")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRepairService.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("AutoRepairService.Domain.Entities.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Card", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.CustomerProfile", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Payments");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.MechanicBankAccount", b =>
                {
                    b.Navigation("PayMents");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.MechanicProfile", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Payments");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Part", b =>
                {
                    b.Navigation("ServiceParts");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Service", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ServiceParts");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.User", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("MechanicProfile");

                    b.Navigation("Profile");

                    b.Navigation("UserRoles");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoRepairService.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
